#!/usr/bin/env bash
# sandboxshift-setup.sh — One-command AWS infrastructure bootstrap for SandboxShift.
#
# What this script does:
#   1. Detects your AWS account ID and default region automatically
#   2. Creates an S3 bucket for Terraform remote state (with versioning + encryption)
#   3. Creates a DynamoDB table for Terraform state locking
#   4. Patches terraform/fargate/backend.tf with the real bucket name
#   5. Runs terraform init + terraform apply (region is the only required var)
#   6. Prints the FARGATE_* env vars ready to paste into your shell profile
#
# Usage:
#   chmod +x sandboxshift-setup.sh
#   ./sandboxshift-setup.sh
#
# Optional env var overrides (all have sensible defaults):
#   AWS_REGION           Override region (default: auto-detected from AWS config)
#   SANDBOXSHIFT_ENV     Deployment tag (default: dev)
#
# Requirements:
#   - aws CLI configured (aws configure or AWS_PROFILE)
#   - terraform >= 1.5 installed
#   - jq installed (brew install jq)

set -euo pipefail

# ───────────────────────────────────────────────────────────────────────────────
# Helpers
# ───────────────────────────────────────────────────────────────────────────────

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

info()  { echo -e "${BLUE}[sandboxshift]${NC} $*"; }
ok()    { echo -e "${GREEN}[sandboxshift]${NC} ✓ $*"; }
warn()  { echo -e "${YELLOW}[sandboxshift]${NC} ⚠ $*"; }
error() { echo -e "${RED}[sandboxshift]${NC} ✗ $*" >&2; exit 1; }

check_dependency() {
  command -v "$1" &>/dev/null || error "'$1' is required but not installed. $2"
}

# ───────────────────────────────────────────────────────────────────────────────
# Preflight checks
# ───────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BLUE}██████████████████████████████████████████████${NC}"
echo -e "${BLUE}  SandboxShift — AWS Infrastructure Setup${NC}"
echo -e "${BLUE}██████████████████████████████████████████████${NC}"
echo ""

check_dependency aws  "Install with: brew install awscli"
check_dependency terraform "Install with: brew install terraform"
check_dependency jq   "Install with: brew install jq"

# Must be run from the repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/terraform/fargate"
[[ -f "${TF_DIR}/main.tf" ]] || error "Run this script from the sandboxshift repo root."

# ───────────────────────────────────────────────────────────────────────────────
# Detect AWS identity
# ───────────────────────────────────────────────────────────────────────────────

info "Detecting AWS identity..."
IDENTITY=$(aws sts get-caller-identity 2>/dev/null) \
  || error "AWS credentials not configured. Run 'aws configure' first."

ACCOUNT_ID=$(echo "${IDENTITY}" | jq -r '.Account')
CALLER_ARN=$(echo "${IDENTITY}" | jq -r '.Arn')

# Region: env var > AWS_DEFAULT_REGION > aws config > prompt
if [[ -n "${AWS_REGION:-}" ]]; then
  REGION="${AWS_REGION}"
elif [[ -n "${AWS_DEFAULT_REGION:-}" ]]; then
  REGION="${AWS_DEFAULT_REGION}"
else
  REGION=$(aws configure get region 2>/dev/null || true)
  if [[ -z "${REGION}" ]]; then
    echo -n "Enter AWS region (e.g. us-east-1): "
    read -r REGION
    [[ -n "${REGION}" ]] || error "Region is required."
  fi
fi

ENV_TAG="${SANDBOXSHIFT_ENV:-dev}"

ok "Account: ${ACCOUNT_ID}"
ok "Region:  ${REGION}"
ok "Caller:  ${CALLER_ARN}"
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Generate unique names for the Terraform state bucket and DynamoDB lock table.
# The workspace S3 bucket name is auto-generated by Terraform itself
# (random_id + account ID in main.tf locals) — no user input required.
# ───────────────────────────────────────────────────────────────────────────────

# Persistent hash: stored in ~/.sandboxshift/setup.env so re-running
# the script uses the same state bucket names (idempotent).
SETUP_ENV="${HOME}/.sandboxshift/setup.env"
mkdir -p "${HOME}/.sandboxshift"

if [[ -f "${SETUP_ENV}" ]]; then
  # shellcheck disable=SC1090
  source "${SETUP_ENV}"
  info "Reusing existing setup: ${SETUP_ENV}"
else
  RAND_HASH=$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 6)
  STATE_BUCKET="sandboxshift-tfstate-${ACCOUNT_ID}-${RAND_HASH}"
  LOCK_TABLE="sandboxshift-tfstate-lock-${RAND_HASH}"

  cat > "${SETUP_ENV}" <<EOF
# SandboxShift setup — auto-generated by sandboxshift-setup.sh
# Do not edit manually.
RAND_HASH=${RAND_HASH}
STATE_BUCKET=${STATE_BUCKET}
LOCK_TABLE=${LOCK_TABLE}
ACCOUNT_ID=${ACCOUNT_ID}
REGION=${REGION}
EOF
  ok "Generated unique names (saved to ${SETUP_ENV})"
fi

info "State bucket: ${STATE_BUCKET}"
info "Lock table:   ${LOCK_TABLE}"
info "Workspace bucket: auto-generated by Terraform (sandboxshift-ws-{account}-{hash})"
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Step 1: S3 state bucket
# ───────────────────────────────────────────────────────────────────────────────

if aws s3api head-bucket --bucket "${STATE_BUCKET}" --region "${REGION}" 2>/dev/null; then
  ok "State bucket already exists: ${STATE_BUCKET}"
else
  info "Creating state bucket: ${STATE_BUCKET}"
  if [[ "${REGION}" == "us-east-1" ]]; then
    aws s3api create-bucket \
      --bucket "${STATE_BUCKET}" \
      --region "${REGION}" \
      --output text > /dev/null
  else
    aws s3api create-bucket \
      --bucket "${STATE_BUCKET}" \
      --region "${REGION}" \
      --create-bucket-configuration LocationConstraint="${REGION}" \
      --output text > /dev/null
  fi

  aws s3api put-bucket-versioning \
    --bucket "${STATE_BUCKET}" \
    --versioning-configuration Status=Enabled

  aws s3api put-bucket-encryption \
    --bucket "${STATE_BUCKET}" \
    --server-side-encryption-configuration \
      '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

  aws s3api put-public-access-block \
    --bucket "${STATE_BUCKET}" \
    --public-access-block-configuration \
      BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

  ok "State bucket created and secured."
fi

# ───────────────────────────────────────────────────────────────────────────────
# Step 2: DynamoDB lock table
# ───────────────────────────────────────────────────────────────────────────────

LOCK_STATUS=$(aws dynamodb describe-table \
  --table-name "${LOCK_TABLE}" \
  --region "${REGION}" \
  --query 'Table.TableStatus' \
  --output text 2>/dev/null || echo "NOT_FOUND")

if [[ "${LOCK_STATUS}" != "NOT_FOUND" ]]; then
  ok "DynamoDB lock table already exists: ${LOCK_TABLE}"
else
  info "Creating DynamoDB lock table: ${LOCK_TABLE}"
  aws dynamodb create-table \
    --table-name "${LOCK_TABLE}" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "${REGION}" \
    --output text > /dev/null

  info "Waiting for table to become active..."
  aws dynamodb wait table-exists \
    --table-name "${LOCK_TABLE}" \
    --region "${REGION}"
  ok "DynamoDB lock table created."
fi

# ───────────────────────────────────────────────────────────────────────────────
# Step 3: Patch backend.tf with real bucket and table names
# ───────────────────────────────────────────────────────────────────────────────

info "Patching terraform/fargate/backend.tf..."
cat > "${TF_DIR}/backend.tf" <<EOF
# Auto-generated by sandboxshift-setup.sh — do not edit manually.
# Re-run ./sandboxshift-setup.sh to regenerate.
terraform {
  backend "s3" {
    bucket         = "${STATE_BUCKET}"
    key            = "sandboxshift/fargate/terraform.tfstate"
    region         = "${REGION}"
    encrypt        = true
    dynamodb_table = "${LOCK_TABLE}"
  }
}
EOF
ok "backend.tf patched."

# ───────────────────────────────────────────────────────────────────────────────
# Step 4: terraform init
# ───────────────────────────────────────────────────────────────────────────────

info "Running terraform init..."
cd "${TF_DIR}"
terraform init -reconfigure \
  -backend-config="bucket=${STATE_BUCKET}" \
  -backend-config="key=sandboxshift/fargate/terraform.tfstate" \
  -backend-config="region=${REGION}" \
  -backend-config="dynamodb_table=${LOCK_TABLE}" \
  -backend-config="encrypt=true"
ok "terraform init complete."
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Step 5: terraform apply — only aws_region is required; everything else is
# either defaulted or auto-computed (workspace bucket name, etc.)
# ───────────────────────────────────────────────────────────────────────────────

info "Running terraform apply..."
terraform apply -auto-approve \
  -var="aws_region=${REGION}" \
  -var="environment=${ENV_TAG}"
ok "terraform apply complete."
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Step 6: Read outputs and write env vars
# ───────────────────────────────────────────────────────────────────────────────

info "Reading terraform outputs..."
TF_OUTPUTS=$(terraform output -json)

CLUSTER_ARN=$(echo "${TF_OUTPUTS}"         | jq -r '.cluster_arn.value')
TASK_DEF_ARN=$(echo "${TF_OUTPUTS}"        | jq -r '.task_def_arn.value')
LOG_GROUP=$(echo "${TF_OUTPUTS}"           | jq -r '.log_group.value')
SUBNET_IDS_JSON=$(echo "${TF_OUTPUTS}"     | jq -r '.subnet_ids.value | join(",")')
SEC_GROUP_IDS=$(echo "${TF_OUTPUTS}"       | jq -r '.security_group_ids.value | join(",")')
WORKSPACE_BUCKET=$(echo "${TF_OUTPUTS}"   | jq -r '.workspace_bucket_name.value')

# Write env vars to ~/.sandboxshift/fargate.env for easy sourcing
FARGATE_ENV="${HOME}/.sandboxshift/fargate.env"
cat > "${FARGATE_ENV}" <<EOF
# SandboxShift Fargate env vars — auto-generated by sandboxshift-setup.sh
# Source this file or add these exports to your ~/.zshrc / ~/.bashrc:
#   source ~/.sandboxshift/fargate.env
export FARGATE_CLUSTER_ARN="${CLUSTER_ARN}"
export FARGATE_TASK_DEFINITION_ARN="${TASK_DEF_ARN}"
export FARGATE_SUBNET_IDS="${SUBNET_IDS_JSON}"
export FARGATE_SECURITY_GROUP_IDS="${SEC_GROUP_IDS}"
export FARGATE_LOG_GROUP="${LOG_GROUP}"
export FARGATE_REGION="${REGION}"
export FARGATE_WORKSPACE_BUCKET="${WORKSPACE_BUCKET}"
EOF

ok "Env vars saved to ${FARGATE_ENV}"
echo ""

echo -e "  Workspace bucket: ${YELLOW}${WORKSPACE_BUCKET}${NC}"
echo ""

# ───────────────────────────────────────────────────────────────────────────────
# Done — print summary
# ───────────────────────────────────────────────────────────────────────────────

echo -e "${GREEN}"
echo "  ██████████████████████████████████████████████"
echo "  SandboxShift AWS setup complete!"
echo "  ██████████████████████████████████████████████"
echo -e "${NC}"
echo "  To activate in your current shell:"
echo ""
echo -e "    ${YELLOW}source ~/.sandboxshift/fargate.env${NC}"
echo ""
echo "  To activate permanently, add to ~/.zshrc or ~/.bashrc:"
echo ""
echo -e "    ${YELLOW}echo 'source ~/.sandboxshift/fargate.env' >> ~/.zshrc${NC}"
echo ""
echo "  Then run:"
echo ""
echo -e "    ${YELLOW}sandboxshift run /tmp/my-project \"echo hello from fargate\" --ram-threshold 999${NC}"
echo ""
