"""SandboxShift CLI — sandboxshift run / sandboxshift list / sandboxshift stop / sandboxshift audit tail."""

from __future__ import annotations

import argparse
import asyncio
import ipaddress
import json
import os
import re
import sys
from pathlib import Path

from ..config import SandboxConfig
from ..config_loader import load_workspace_config
from ..observability.audit import AuditLogger
from ..sandbox.burst.engine import BurstEngine
from ..sandbox.detection.sensitivity import SensitivityScanner
from ..sandbox.manager import (
    CloudRuntimeRequiredError,
    RunResult,
    SandboxManager,
    SensitivityBlockedError,
)
from ..sandbox.runtime.fargate import FargateRuntime
from ..sandbox.runtime.podman import PodmanRuntime

# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_DEFAULT_AUDIT_LOG: Path = Path.home() / ".sandboxshift" / "audit.log"
_FARGATE_ENV_FILE: Path = Path.home() / ".sandboxshift" / "fargate.env"
_SERVERS_FILE: Path = Path.home() / ".sandboxshift" / "servers.json"

_SENSITIVE_ROOTS: tuple[Path, ...] = (
    Path.home() / ".aws",
    Path.home() / ".ssh",
    Path.home() / ".gnupg",
    Path("/etc"),
    Path("/proc"),
    Path("/sys"),
    Path("/root"),
)

# Required Fargate env vars (Decision #64: task_def_arn replaced by
# execution_role_arn + task_role_arn; ECR image passed separately).
# FARGATE_ECR_IMAGE is optional — absent = Docker Hub default image.
_FARGATE_ENV_VARS: list[str] = [
    "FARGATE_CLUSTER_ARN",
    "FARGATE_EXECUTION_ROLE_ARN",
    "FARGATE_TASK_ROLE_ARN",
    "FARGATE_SUBNET_IDS",
    "FARGATE_SECURITY_GROUP_IDS",
    "FARGATE_LOG_GROUP",
    "FARGATE_REGION",
    "FARGATE_WORKSPACE_BUCKET",
]

# FQDN regex: requires at least two labels separated by dots.
_FQDN_RE = re.compile(
    r"^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?)+$",
    re.IGNORECASE,
)

_MEMORY_MB_MIN = 128
_MEMORY_MB_MAX = 65536
_CPU_MIN = 0.25
_CPU_MAX = 64.0

# Hardcoded last-resort defaults used when neither CLI flag nor YAML provides a value.
_DEFAULT_CPU = 1.0
_DEFAULT_MEMORY_MB = 512
_DEFAULT_TIMEOUT = 1800


# ---------------------------------------------------------------------------
# Auto-load ~/.sandboxshift/fargate.env
# ---------------------------------------------------------------------------

def _load_fargate_env() -> None:
    """Load vars from ~/.sandboxshift/fargate.env into os.environ.

    FARGATE_* keys are always overwritten — they are machine-generated by
    sandboxshift-setup.sh and must always reflect the latest infrastructure
    state.

    All other keys (e.g. SANDBOXSHIFT_AUDIT_LOG) are only set if not already
    present in the environment, so intentional shell overrides still work.

    Parses lines of the form:
        export KEY="VALUE"
        export KEY=VALUE
    Silently ignores comments, blank lines, and malformed lines.
    """
    if not _FARGATE_ENV_FILE.exists():
        return
    try:
        text = _FARGATE_ENV_FILE.read_text(encoding="utf-8")
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            continue
        # FARGATE_* vars are always overwritten — stale shell exports must not
        # survive a setup script re-run.
        if key.startswith("FARGATE_") or key not in os.environ:
            os.environ[key] = value


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _validate_workspace(workspace_str: str) -> Path:
    """Validate workspace path: must exist and must not be a sensitive root."""
    p = Path(workspace_str).expanduser()
    if not p.exists():
        print(f"Error: workspace does not exist: {workspace_str!r}", file=sys.stderr)
        sys.exit(1)
    resolved = p.resolve()
    for sensitive in _SENSITIVE_ROOTS:
        try:
            sensitive_resolved = sensitive.resolve()
            if resolved == sensitive_resolved or sensitive_resolved in resolved.parents:
                print(
                    f"Error: workspace {resolved!r} is inside a protected directory"
                    f" ({sensitive_resolved}). Refusing to run.",
                    file=sys.stderr,
                )
                sys.exit(1)
        except Exception:  # noqa: BLE001
            pass
    return resolved


def _validate_allow_hosts(hosts: list[str]) -> None:
    """Reject bare IP addresses and non-FQDN values in --allow.

    "*" is accepted as a special sentinel for unrestricted network mode
    (Decision #54). All other entries must be FQDNs — bare IPs including
    IMDS 169.254.169.254 are rejected.
    """
    for host in hosts:
        # "*" is the unrestricted-network sentinel — bypass all checks.
        if host == "*":
            continue
        # Reject bare IP addresses outright (IPv4 and IPv6).
        try:
            ipaddress.ip_address(host)
            print(
                f"Error: --allow does not accept IP addresses: {host!r}. Use FQDNs only.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass
        # Require a valid FQDN (at least two dot-separated labels).
        if not _FQDN_RE.match(host):
            print(
                f"Error: --allow requires a valid fully-qualified domain name: {host!r}",
                file=sys.stderr,
            )
            sys.exit(1)


def _parse_port(port_str: str) -> tuple[int, int]:
    """Parse port string. Accepts bare PORT or HOST:CONTAINER format.

    Bare port (e.g. '3000') expands to (3000, 3000) — same host and container port.
    HOST:CONTAINER (e.g. '8080:3000') maps host 8080 to container 3000.

    Raises ValueError on invalid input.
    """
    parts = port_str.split(":")
    if len(parts) == 1:
        # Bare port number — expand to HOST:CONTAINER both equal.
        try:
            port = int(parts[0])
        except ValueError:
            raise ValueError(
                f"Invalid port '{port_str}': must be an integer (e.g. 3000) "
                f"or HOST:CONTAINER (e.g. 8080:3000)"
            )
        if not (1 <= port <= 65535):
            raise ValueError(f"Port {port} out of valid range (1-65535)")
        return (port, port)
    if len(parts) != 2:
        raise ValueError(
            f"Invalid port format '{port_str}': expected PORT or HOST:CONTAINER "
            f"(e.g. 3000 or 8080:3000)"
        )
    try:
        host, container = int(parts[0]), int(parts[1])
    except ValueError:
        raise ValueError(f"Port numbers in '{port_str}' must be integers")
    if not (1 <= host <= 65535):
        raise ValueError(f"Host port {host} out of valid range (1-65535)")
    if not (1 <= container <= 65535):
        raise ValueError(f"Container port {container} out of valid range (1-65535)")
    return (host, container)


def _build_fargate_runtime(audit_logger: AuditLogger) -> FargateRuntime | None:
    """Build FargateRuntime from environment variables, or return None if any required vars are missing.

    Required vars (see _FARGATE_ENV_VARS):
      FARGATE_CLUSTER_ARN, FARGATE_EXECUTION_ROLE_ARN, FARGATE_TASK_ROLE_ARN,
      FARGATE_SUBNET_IDS, FARGATE_SECURITY_GROUP_IDS, FARGATE_LOG_GROUP,
      FARGATE_REGION, FARGATE_WORKSPACE_BUCKET

    Optional vars:
      FARGATE_SERVER_SECURITY_GROUP_ID — if absent, server mode tasks will launch
        without ALL-TCP inbound (ports won't be publicly reachable).
      FARGATE_TASK_FAMILY — prefix for dynamic task def family names
        (default: 'sandboxshift-sandbox').
      FARGATE_ECR_IMAGE — full container image URI; if absent or empty,
        defaults to 'sandboxshift/runtime-multi:latest' (Docker Hub).
    """
    values = {k: os.environ.get(k, "").strip() for k in _FARGATE_ENV_VARS}
    if any(v == "" for v in values.values()):
        return None
    server_sg_id = os.environ.get("FARGATE_SERVER_SECURITY_GROUP_ID", "").strip() or None
    task_family = os.environ.get("FARGATE_TASK_FAMILY", "sandboxshift-sandbox").strip()
    ecr_image = os.environ.get("FARGATE_ECR_IMAGE", "").strip()
    return FargateRuntime(
        cluster_arn=values["FARGATE_CLUSTER_ARN"],
        execution_role_arn=values["FARGATE_EXECUTION_ROLE_ARN"],
        task_role_arn=values["FARGATE_TASK_ROLE_ARN"],
        subnet_ids=values["FARGATE_SUBNET_IDS"].split(","),
        security_group_ids=values["FARGATE_SECURITY_GROUP_IDS"].split(","),
        region=values["FARGATE_REGION"],
        log_group=values["FARGATE_LOG_GROUP"],
        workspace_bucket=values["FARGATE_WORKSPACE_BUCKET"],
        task_family=task_family,
        ecr_image=ecr_image,
        server_security_group_id=server_sg_id,
        audit_logger=audit_logger,
    )


def _resolve_audit_log(args: argparse.Namespace) -> Path:
    """Resolve audit log path: --audit-log arg → env var → default."""
    if args.audit_log:
        return Path(args.audit_log).expanduser()
    env_val = os.environ.get("SANDBOXSHIFT_AUDIT_LOG", "").strip()
    if env_val:
        return Path(env_val).expanduser()
    return _DEFAULT_AUDIT_LOG


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

async def _run_async(args: argparse.Namespace, workspace: Path) -> RunResult:
    # Load YAML config from workspace (returns {} if sandboxshift.yaml absent).
    yaml_cfg = load_workspace_config(Path(args.workspace))

    # Parse CLI --port flags; exit(1) on invalid input.
    parsed_ports: list[tuple[int, int]] = []
    for port_str in (args.ports or []):
        try:
            parsed_ports.append(_parse_port(port_str))
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

    # Combine YAML ports with CLI ports (YAML first, then CLI), deduped.
    yaml_ports = yaml_cfg.get("ports", [])
    all_ports: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    for p in [*yaml_ports, *parsed_ports]:
        pt = (int(p[0]), int(p[1]))
        if pt not in seen:
            seen.add(pt)
            all_ports.append(pt)

    # For each resource field the merge priority is:
    #   CLI flag (explicit) → sandboxshift.yaml → hardcoded default
    # --cpu / --memory-mb / --timeout default to None in argparse so we can
    # distinguish "user did not pass this flag" from "user passed the value".

    # setup_command: CLI --setup wins over YAML.
    effective_setup = args.setup if args.setup is not None else yaml_cfg.get("setup_command")
    # network_allow: CLI --allow wins over YAML.
    effective_allow = list(args.allow) if args.allow else yaml_cfg.get("network_allow", [])
    # skip_sensitivity_check: CLI --skip-sensitivity-check wins over YAML.
    skip_scan = args.skip_sensitivity_check or yaml_cfg.get("skip_sensitivity_check", False)
    # workspace_readonly: YAML only (no CLI flag in V1).
    workspace_readonly = yaml_cfg.get("workspace_readonly", False)
    # min resource requirements: YAML only (no CLI flags in V1).
    min_cpu_required = yaml_cfg.get("min_cpu_required", 0.0)
    min_memory_mb_required = yaml_cfg.get("min_memory_mb_required", 0)
    # cpu_limit: CLI --cpu wins over YAML resources.cpu.
    effective_cpu = (
        args.cpu if args.cpu is not None
        else yaml_cfg.get("cpu_limit", _DEFAULT_CPU)
    )
    # memory_limit_mb: CLI --memory-mb wins over YAML resources.memory.
    effective_memory_mb = (
        args.memory_mb if args.memory_mb is not None
        else yaml_cfg.get("memory_limit_mb", _DEFAULT_MEMORY_MB)
    )
    # timeout_seconds: CLI --timeout wins over YAML sandbox.timeout.
    effective_timeout = (
        args.timeout if args.timeout is not None
        else yaml_cfg.get("timeout_seconds", _DEFAULT_TIMEOUT)
    )

    config = SandboxConfig(
        cpu_limit=effective_cpu,
        memory_limit_mb=effective_memory_mb,
        network_allow=effective_allow,
        timeout_seconds=effective_timeout,
        setup_command=effective_setup,
        ports=all_ports,
        skip_sensitivity_check=skip_scan,
        workspace_readonly=workspace_readonly,
        min_cpu_required=min_cpu_required,
        min_memory_mb_required=min_memory_mb_required,
    )

    audit_log_path = _resolve_audit_log(args)
    audit_logger = AuditLogger(log_path=audit_log_path)

    fargate_runtime = _build_fargate_runtime(audit_logger)
    podman_runtime = PodmanRuntime(audit_logger=audit_logger)

    # Resolve effective run mode.
    # Priority: CLI --mode (if not "auto") > YAML sandbox.mode > --ram-threshold.
    # --mode local  → threshold=0.0      (available RAM always ≥ 0 → always local)
    # --mode cloud  → threshold=+inf     (available RAM never ≥ inf → always cloud)
    # --mode auto   → check YAML sandbox.mode, then fall back to --ram-threshold
    effective_mode = args.mode if args.mode != "auto" else yaml_cfg.get("sandbox_mode", "auto")
    if effective_mode == "local":
        effective_threshold_gb = 0.0
    elif effective_mode == "cloud":
        effective_threshold_gb = float("inf")
    else:  # auto
        effective_threshold_gb = args.ram_threshold / 1024

    burst_engine = BurstEngine(ram_threshold_gb=effective_threshold_gb)

    manager = SandboxManager(
        local_runtime=podman_runtime,
        cloud_runtime=fargate_runtime,
        burst_engine=burst_engine,
        scanner=SensitivityScanner(),
        audit_logger=audit_logger,
    )

    return await manager.run(workspace=workspace, task=args.task, config=config)


def _cmd_run(args: argparse.Namespace) -> None:
    """Handle 'sandboxshift run' subcommand."""
    _load_fargate_env()
    workspace = _validate_workspace(args.workspace)

    if args.allow:
        _validate_allow_hosts(list(args.allow))

    # Bounds check memory and cpu only when the flag was explicitly passed.
    # When the value is None the YAML fallback (applied in _run_async) takes
    # effect — bounds on YAML-sourced values are enforced by the Fargate API.
    if args.memory_mb is not None and not (_MEMORY_MB_MIN <= args.memory_mb <= _MEMORY_MB_MAX):
        print(
            f"Error: --memory-mb must be between {_MEMORY_MB_MIN} and {_MEMORY_MB_MAX}",
            file=sys.stderr,
        )
        sys.exit(1)
    if args.cpu is not None and not (_CPU_MIN <= args.cpu <= _CPU_MAX):
        print(
            f"Error: --cpu must be between {_CPU_MIN} and {_CPU_MAX}",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        result = asyncio.run(_run_async(args, workspace))
    except SensitivityBlockedError as e:
        print(f"Blocked: {e}", file=sys.stderr)
        sys.exit(2)
    except CloudRuntimeRequiredError as e:
        print(f"Cloud runtime required but not configured: {e}", file=sys.stderr)
        sys.exit(3)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Runtime: {result.runtime_mode}")
    print(f"Duration: {result.duration_seconds:.2f}s")
    print(f"Exit code: {result.task_result.exit_code}")
    if result.task_result.stdout:
        print(result.task_result.stdout)
    if result.task_result.stderr:
        print(result.task_result.stderr, file=sys.stderr)

    sys.exit(result.task_result.exit_code)


def _cmd_list(args: argparse.Namespace) -> None:  # noqa: ARG001
    """Handle 'sandboxshift list' subcommand.

    Reads ~/.sandboxshift/servers.json and prints a table of running cloud
    server tasks. Each row shows: instance ID, public URL(s), and region.

    servers.json is written by FargateRuntime._save_server_info() every time
    a server task starts, and cleaned up by 'sandboxshift stop'. If the user
    closed their terminal without stopping, entries remain here and can be
    stopped with 'sandboxshift stop <instance_id>'.
    """
    if not _SERVERS_FILE.exists():
        print("No running cloud servers found.")
        return

    try:
        servers: dict = json.loads(_SERVERS_FILE.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001
        print(f"Error reading servers file: {e}", file=sys.stderr)
        sys.exit(1)

    if not servers:
        print("No running cloud servers found.")
        return

    # Column widths
    id_w = 24
    url_w = 45

    print(f"{'INSTANCE ID':<{id_w}}  {'URL(S)':<{url_w}}  REGION")
    print("-" * (id_w + url_w + 12))
    for sid, info in servers.items():
        public_ip = info.get("public_ip")
        ports = info.get("ports", [])
        region = info.get("region", "unknown")
        if public_ip and ports:
            urls = "  ".join(f"http://{public_ip}:{c}" for _, c in ports)
        elif public_ip:
            urls = public_ip
        else:
            urls = "(IP pending — check ECS console)"
        print(f"{sid:<{id_w}}  {urls:<{url_w}}  {region}")

    print()
    print(f"Use 'sandboxshift stop <instance_id>' to stop a running server.")


def _cmd_stop(args: argparse.Namespace) -> None:
    """Handle 'sandboxshift stop <instance_id>' subcommand.

    Stops a running cloud server task launched by FargateRuntime in server mode.
    Reads task info from ~/.sandboxshift/servers.json, calls ECS stop_task,
    and removes the entry from the file.
    """
    _load_fargate_env()

    import boto3  # local import — only needed for this subcommand

    if not _SERVERS_FILE.exists():
        print("No running cloud servers found.", file=sys.stderr)
        sys.exit(1)

    try:
        servers: dict = json.loads(_SERVERS_FILE.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"Error reading servers file: {e}", file=sys.stderr)
        sys.exit(1)

    instance_id = args.instance_id

    if instance_id not in servers:
        print(f"No server found with instance ID: {instance_id}", file=sys.stderr)
        if servers:
            print("Running servers:")
            for sid, info in servers.items():
                ip = info.get("public_ip", "unknown")
                ports = info.get("ports", [])
                urls = ", ".join(f"http://{ip}:{c}" for _, c in ports) if ip else sid
                print(f"  {sid}  {urls}")
        sys.exit(1)

    info = servers[instance_id]
    region = info.get("region") or os.environ.get("FARGATE_REGION", "")
    cluster_arn = info.get("cluster_arn", "")
    ecs_task_arn = info.get("ecs_task_arn", "")

    if not region or not cluster_arn or not ecs_task_arn:
        print(
            f"Error: incomplete server info for {instance_id} — "
            "cannot stop task. Stop it manually via the AWS console.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        session = boto3.Session()
        ecs = session.client("ecs", region_name=region)
        ecs.stop_task(
            cluster=cluster_arn,
            task=ecs_task_arn,
            reason="sandboxshift stop command",
        )
        print(f"Stopped server {instance_id}")

        # Remove from servers.json
        del servers[instance_id]
        _SERVERS_FILE.write_text(json.dumps(servers, indent=2), encoding="utf-8")

    except Exception as e:
        print(f"Error stopping task: {e}", file=sys.stderr)
        sys.exit(1)


def _cmd_audit_tail(args: argparse.Namespace) -> None:
    """Handle 'sandboxshift audit tail' subcommand."""
    _load_fargate_env()
    audit_log_path = _resolve_audit_log(args)

    if not audit_log_path.exists():
        print(f"No audit log found at {audit_log_path}")
        return

    try:
        lines = audit_log_path.read_text(encoding="utf-8").splitlines()
    except OSError as e:
        print(f"Error reading audit log: {e}", file=sys.stderr)
        sys.exit(1)

    n = getattr(args, "lines", 20)
    tail = lines[-n:] if len(lines) > n else lines

    for line in tail:
        try:
            entry = json.loads(line)
            print(json.dumps(entry, indent=2))
        except json.JSONDecodeError:
            print(line)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sandboxshift",
        description="Run AI agent tasks in isolated sandboxes (local or cloud)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # ── sandboxshift run ──────────────────────────────────────────────────────
    run_parser = subparsers.add_parser("run", help="Run a task in a sandbox")
    run_parser.add_argument("workspace", help="Path to workspace directory")
    run_parser.add_argument("task", help="Shell command to run")
    run_parser.add_argument(
        "--mode",
        choices=["local", "cloud", "auto"],
        default="auto",
        help=(
            "Run mode: 'local' (always run in Podman), 'cloud' (always burst to Fargate), "
            "'auto' (default — decide based on available RAM and --ram-threshold). "
            "Overrides YAML sandbox.mode. Never overrides sensitive-data detection."
        ),
    )
    run_parser.add_argument(
        "--memory-mb",
        dest="memory_mb",
        type=int,
        default=None,
        help=(
            "Memory limit in MB (default: from sandboxshift.yaml resources.memory, "
            f"or {_DEFAULT_MEMORY_MB} MB if not set). "
            "For cloud: baked into the ECS task definition registered per run."
        ),
    )
    run_parser.add_argument(
        "--cpu",
        type=float,
        default=None,
        help=(
            "CPU limit in vCPUs (default: from sandboxshift.yaml resources.cpu, "
            f"or {_DEFAULT_CPU} vCPU if not set). "
            "For cloud: baked into the ECS task definition registered per run."
        ),
    )
    run_parser.add_argument(
        "--timeout",
        type=int,
        default=None,
        help=(
            "Task timeout in seconds (default: from sandboxshift.yaml sandbox.timeout, "
            f"or {_DEFAULT_TIMEOUT}s if not set)."
        ),
    )
    run_parser.add_argument(
        "--allow",
        action="append",
        default=[],
        metavar="FQDN",
        help="Allow outbound access to FQDN (repeat for multiple). Use '*' for unrestricted.",
    )
    run_parser.add_argument(
        "--setup",
        default=None,
        help="Setup command to run before the task",
    )
    run_parser.add_argument(
        "--port",
        dest="ports",
        action="append",
        default=[],
        metavar="PORT|HOST:CONTAINER",
        help="Expose container port (e.g. 3000 or 8080:3000). Repeat for multiple.",
    )
    run_parser.add_argument(
        "--ram-threshold",
        dest="ram_threshold",
        type=int,
        default=1024,
        help=(
            "Available RAM threshold in MB. If available RAM < N, burst to cloud "
            "(default: 1024). Only used when --mode is 'auto'."
        ),
    )
    run_parser.add_argument(
        "--skip-sensitivity-check",
        dest="skip_sensitivity_check",
        action="store_true",
        default=False,
        help="Skip sensitive data detection (use with caution)",
    )
    run_parser.add_argument(
        "--audit-log",
        dest="audit_log",
        default=None,
        help="Path to audit log file (default: ~/.sandboxshift/audit.log)",
    )
    run_parser.set_defaults(func=_cmd_run)

    # ── sandboxshift list ─────────────────────────────────────────────────
    list_parser = subparsers.add_parser(
        "list",
        help="List running cloud server tasks",
    )
    list_parser.set_defaults(func=_cmd_list)

    # ── sandboxshift stop ─────────────────────────────────────────────────
    stop_parser = subparsers.add_parser(
        "stop",
        help="Stop a running cloud server task",
    )
    stop_parser.add_argument(
        "instance_id",
        help="Instance ID printed by 'sandboxshift run' (e.g. ss-abc123def456)",
    )
    stop_parser.set_defaults(func=_cmd_stop)

    # ── sandboxshift audit ─────────────────────────────────────────────────
    audit_parser = subparsers.add_parser("audit", help="Audit trail commands")
    audit_subparsers = audit_parser.add_subparsers(dest="audit_command", required=True)

    tail_parser = audit_subparsers.add_parser("tail", help="Show recent audit log entries")
    tail_parser.add_argument(
        "-n",
        dest="lines",
        type=int,
        default=20,
        help="Number of recent entries to show (default: 20)",
    )
    tail_parser.add_argument(
        "--audit-log",
        dest="audit_log",
        default=None,
        help="Path to audit log file (default: ~/.sandboxshift/audit.log)",
    )
    tail_parser.set_defaults(func=_cmd_audit_tail)

    return parser


def main() -> None:
    """Entry point for the sandboxshift CLI."""
    parser = _build_parser()
    args = parser.parse_args()
    args.func(args)
