"""SandboxShift CLI — sandboxshift run / sandboxshift audit tail."""

from __future__ import annotations

import argparse
import asyncio
import ipaddress
import json
import os
import re
import sys
from pathlib import Path

from ..config import SandboxConfig
from ..config_loader import load_workspace_config
from ..observability.audit import AuditLogger
from ..sandbox.burst.engine import BurstEngine
from ..sandbox.detection.sensitivity import SensitivityScanner
from ..sandbox.manager import (
    CloudRuntimeRequiredError,
    RunResult,
    SandboxManager,
    SensitivityBlockedError,
)
from ..sandbox.runtime.fargate import FargateRuntime
from ..sandbox.runtime.podman import PodmanRuntime

# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_DEFAULT_AUDIT_LOG: Path = Path.home() / ".sandboxshift" / "audit.log"
_FARGATE_ENV_FILE: Path = Path.home() / ".sandboxshift" / "fargate.env"

_SENSITIVE_ROOTS: tuple[Path, ...] = (
    Path.home() / ".aws",
    Path.home() / ".ssh",
    Path.home() / ".gnupg",
    Path("/etc"),
    Path("/proc"),
    Path("/sys"),
    Path("/root"),
)

_FARGATE_ENV_VARS: list[str] = [
    "FARGATE_CLUSTER_ARN",
    "FARGATE_TASK_DEFINITION_ARN",
    "FARGATE_SUBNET_IDS",
    "FARGATE_SECURITY_GROUP_IDS",
    "FARGATE_LOG_GROUP",
    "FARGATE_REGION",
    "FARGATE_WORKSPACE_BUCKET",
]

# FQDN regex: requires at least two labels separated by dots.
_FQDN_RE = re.compile(
    r"^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?)+$",
    re.IGNORECASE,
)

_MEMORY_MB_MIN = 128
_MEMORY_MB_MAX = 65536
_CPU_MIN = 0.25
_CPU_MAX = 64.0


# ---------------------------------------------------------------------------
# Auto-load ~/.sandboxshift/fargate.env
# ---------------------------------------------------------------------------

def _load_fargate_env() -> None:
    """Load vars from ~/.sandboxshift/fargate.env into os.environ.

    FARGATE_* keys are always overwritten — they are machine-generated by
    sandboxshift-setup.sh and must always reflect the latest infrastructure
    state. Stale shell exports (e.g. from a previous 'source fargate.env')
    would otherwise point at deregistered task definition revisions.

    All other keys (e.g. SANDBOXSHIFT_AUDIT_LOG) are only set if not already
    present in the environment, so intentional shell overrides still work.

    Parses lines of the form:
        export KEY="VALUE"
        export KEY=VALUE
    Silently ignores comments, blank lines, and malformed lines.
    """
    if not _FARGATE_ENV_FILE.exists():
        return
    try:
        text = _FARGATE_ENV_FILE.read_text(encoding="utf-8")
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            continue
        # FARGATE_* vars are always overwritten — stale shell exports must not
        # survive a setup script re-run that creates a new task definition revision.
        if key.startswith("FARGATE_") or key not in os.environ:
            os.environ[key] = value


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _validate_workspace(workspace_str: str) -> Path:
    """Validate workspace path: must exist and must not be a sensitive root."""
    p = Path(workspace_str).expanduser()
    if not p.exists():
        print(f"Error: workspace does not exist: {workspace_str!r}", file=sys.stderr)
        sys.exit(1)
    resolved = p.resolve()
    for sensitive in _SENSITIVE_ROOTS:
        try:
            sensitive_resolved = sensitive.resolve()
            if resolved == sensitive_resolved or sensitive_resolved in resolved.parents:
                print(
                    f"Error: workspace {resolved!r} is inside a protected directory"
                    f" ({sensitive_resolved}). Refusing to run.",
                    file=sys.stderr,
                )
                sys.exit(1)
        except Exception:  # noqa: BLE001
            pass
    return resolved


def _validate_allow_hosts(hosts: list[str]) -> None:
    """Reject bare IP addresses and non-FQDN values in --allow.

    "*" is accepted as a special sentinel for unrestricted network mode
    (Decision #54). All other entries must be FQDNs — bare IPs including
    IMDS 169.254.169.254 are rejected.
    """
    for host in hosts:
        # "*" is the unrestricted-network sentinel — bypass all checks.
        if host == "*":
            continue
        # Reject bare IP addresses outright (IPv4 and IPv6).
        try:
            ipaddress.ip_address(host)
            print(
                f"Error: --allow does not accept IP addresses: {host!r}. Use FQDNs only.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass
        # Require a valid FQDN (at least two dot-separated labels).
        if not _FQDN_RE.match(host):
            print(
                f"Error: --allow requires a valid fully-qualified domain name: {host!r}",
                file=sys.stderr,
            )
            sys.exit(1)


def _parse_port(port_str: str) -> tuple[int, int]:
    """Parse 'HOST:CONTAINER' string. Raises ValueError on invalid input."""
    parts = port_str.split(":")
    if len(parts) != 2:
        raise ValueError(
            f"Invalid port format '{port_str}': expected HOST:CONTAINER (e.g. 8000:8000)"
        )
    try:
        host, container = int(parts[0]), int(parts[1])
    except ValueError:
        raise ValueError(f"Port numbers in '{port_str}' must be integers")
    if not (1 <= host <= 65535):
        raise ValueError(f"Host port {host} out of valid range (1-65535)")
    if not (1 <= container <= 65535):
        raise ValueError(f"Container port {container} out of valid range (1-65535)")
    return (host, container)


def _build_fargate_runtime(audit_logger: AuditLogger) -> FargateRuntime | None:
    """Build FargateRuntime from environment variables, or return None if any are missing."""
    values = {k: os.environ.get(k, "").strip() for k in _FARGATE_ENV_VARS}
    if any(v == "" for v in values.values()):
        return None
    return FargateRuntime(
        cluster_arn=values["FARGATE_CLUSTER_ARN"],
        task_def_arn=values["FARGATE_TASK_DEFINITION_ARN"],
        subnet_ids=values["FARGATE_SUBNET_IDS"].split(","),
        security_group_ids=values["FARGATE_SECURITY_GROUP_IDS"].split(","),
        region=values["FARGATE_REGION"],
        log_group=values["FARGATE_LOG_GROUP"],
        workspace_bucket=values["FARGATE_WORKSPACE_BUCKET"],
        audit_logger=audit_logger,
    )


def _resolve_audit_log(args: argparse.Namespace) -> Path:
    """Resolve audit log path: --audit-log arg → env var → default."""
    if args.audit_log:
        return Path(args.audit_log).expanduser()
    env_val = os.environ.get("SANDBOXSHIFT_AUDIT_LOG", "").strip()
    if env_val:
        return Path(env_val).expanduser()
    return _DEFAULT_AUDIT_LOG


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

async def _run_async(args: argparse.Namespace, workspace: Path) -> RunResult:
    # Load YAML config from workspace (returns {} if sandboxshift.yaml absent).
    yaml_cfg = load_workspace_config(Path(args.workspace))

    # Parse CLI --port flags; exit(1) on invalid input.
    parsed_ports: list[tuple[int, int]] = []
    for port_str in (args.ports or []):
        try:
            parsed_ports.append(_parse_port(port_str))
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

    # Combine YAML ports with CLI ports (YAML first, then CLI), deduped.
    yaml_ports = yaml_cfg.get("ports", [])
    all_ports: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    for p in [*yaml_ports, *parsed_ports]:
        pt = (int(p[0]), int(p[1]))
        if pt not in seen:
            seen.add(pt)
            all_ports.append(pt)

    # setup_command: CLI --setup wins over YAML.
    effective_setup = args.setup if args.setup is not None else yaml_cfg.get("setup_command")
    # network_allow: CLI --allow wins over YAML.
    effective_allow = list(args.allow) if args.allow else yaml_cfg.get("network_allow", [])
    # skip_sensitivity_check: CLI --skip-sensitivity-check wins over YAML.
    skip_scan = args.skip_sensitivity_check or yaml_cfg.get("skip_sensitivity_check", False)
    # workspace_readonly: YAML only (no CLI flag in V1).
    workspace_readonly = yaml_cfg.get("workspace_readonly", False)
    # min resource requirements: YAML only (no CLI flags in V1).
    min_cpu_required = yaml_cfg.get("min_cpu_required", 0.0)
    min_memory_mb_required = yaml_cfg.get("min_memory_mb_required", 0)

    config = SandboxConfig(
        cpu_limit=args.cpu,
        memory_limit_mb=args.memory_mb,
        network_allow=effective_allow,
        timeout_seconds=args.timeout,
        setup_command=effective_setup,
        ports=all_ports,
        skip_sensitivity_check=skip_scan,
        workspace_readonly=workspace_readonly,
        min_cpu_required=min_cpu_required,
        min_memory_mb_required=min_memory_mb_required,
    )

    audit_log_path = _resolve_audit_log(args)
    audit_logger = AuditLogger(log_path=audit_log_path)

    fargate_runtime = _build_fargate_runtime(audit_logger)
    podman_runtime = PodmanRuntime(audit_logger=audit_logger)
    # --ram-threshold is in MB; BurstEngine expects GB — divide by 1024.
    burst_engine = BurstEngine(ram_threshold_gb=args.ram_threshold / 1024)

    manager = SandboxManager(
        local_runtime=podman_runtime,
        cloud_runtime=fargate_runtime,
        burst_engine=burst_engine,
        scanner=SensitivityScanner(),
        audit_logger=audit_logger,
    )

    return await manager.run(workspace=workspace, task=args.task, config=config)


def _cmd_run(args: argparse.Namespace) -> None:
    """Handle 'sandboxshift run' subcommand."""
    _load_fargate_env()
    workspace = _validate_workspace(args.workspace)

    if args.allow:
        _validate_allow_hosts(list(args.allow))

    # Bounds check memory and cpu (CLI users bypass models.py constraints).
    if not (_MEMORY_MB_MIN <= args.memory_mb <= _MEMORY_MB_MAX):
        print(
            f"Error: --memory-mb must be between {_MEMORY_MB_MIN} and {_MEMORY_MB_MAX}",
            file=sys.stderr,
        )
        sys.exit(1)
    if not (_CPU_MIN <= args.cpu <= _CPU_MAX):
        print(
            f"Error: --cpu must be between {_CPU_MIN} and {_CPU_MAX}",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        result = asyncio.run(_run_async(args, workspace))
    except SensitivityBlockedError as e:
        print(f"Blocked: {e}", file=sys.stderr)
        sys.exit(2)
    except CloudRuntimeRequiredError as e:
        print(f"Cloud runtime required but not configured: {e}", file=sys.stderr)
        sys.exit(3)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Runtime: {result.runtime_mode}")
    print(f"Duration: {result.duration_seconds:.2f}s")
    print(f"Exit code: {result.task_result.exit_code}")
    if result.task_result.stdout:
        print(result.task_result.stdout)
    if result.task_result.stderr:
        print(result.task_result.stderr, file=sys.stderr)

    sys.exit(result.task_result.exit_code)


def _cmd_audit_tail(args: argparse.Namespace) -> None:
    """Handle 'sandboxshift audit tail' subcommand."""
    _load_fargate_env()
    audit_log_path = _resolve_audit_log(args)

    if not audit_log_path.exists():
        print(f"No audit log found at {audit_log_path}")
        return

    try:
        lines = audit_log_path.read_text(encoding="utf-8").splitlines()
    except OSError as e:
        print(f"Error reading audit log: {e}", file=sys.stderr)
        sys.exit(1)

    n = getattr(args, "lines", 20)
    tail = lines[-n:] if len(lines) > n else lines

    for line in tail:
        try:
            entry = json.loads(line)
            print(json.dumps(entry, indent=2))
        except json.JSONDecodeError:
            print(line)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sandboxshift",
        description="Run AI agent tasks in isolated sandboxes (local or cloud)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # ── sandboxshift run ──────────────────────────────────────────────────
    run_parser = subparsers.add_parser("run", help="Run a task in a sandbox")
    run_parser.add_argument("workspace", help="Path to workspace directory")
    run_parser.add_argument("task", help="Shell command to run")
    run_parser.add_argument(
        "--memory-mb",
        dest="memory_mb",
        type=int,
        default=512,
        help="Memory limit in MB (default: 512)",
    )
    run_parser.add_argument(
        "--cpu",
        type=float,
        default=1.0,
        help="CPU limit (default: 1.0)",
    )
    run_parser.add_argument(
        "--timeout",
        type=int,
        default=1800,
        help="Task timeout in seconds (default: 1800)",
    )
    run_parser.add_argument(
        "--allow",
        action="append",
        default=[],
        metavar="FQDN",
        help="Allow outbound access to FQDN (repeat for multiple). Use '*' for unrestricted.",
    )
    run_parser.add_argument(
        "--setup",
        default=None,
        help="Setup command to run before the task",
    )
    run_parser.add_argument(
        "--port",
        dest="ports",
        action="append",
        default=[],
        metavar="HOST:CONTAINER",
        help="Expose container port to host (e.g. 8000:8000). Repeat for multiple.",
    )
    run_parser.add_argument(
        "--ram-threshold",
        dest="ram_threshold",
        type=int,
        default=4096,
        help="Available RAM threshold in MB below which cloud bursting is triggered (default: 4096)",
    )
    run_parser.add_argument(
        "--skip-sensitivity-check",
        dest="skip_sensitivity_check",
        action="store_true",
        default=False,
        help="Skip sensitive data detection (use with caution)",
    )
    run_parser.add_argument(
        "--audit-log",
        dest="audit_log",
        default=None,
        help="Path to audit log file (default: ~/.sandboxshift/audit.log)",
    )
    run_parser.set_defaults(func=_cmd_run)

    # ── sandboxshift audit ────────────────────────────────────────────────
    audit_parser = subparsers.add_parser("audit", help="Audit trail commands")
    audit_subparsers = audit_parser.add_subparsers(dest="audit_command", required=True)

    tail_parser = audit_subparsers.add_parser("tail", help="Show recent audit log entries")
    tail_parser.add_argument(
        "-n",
        dest="lines",
        type=int,
        default=20,
        help="Number of recent entries to show (default: 20)",
    )
    tail_parser.add_argument(
        "--audit-log",
        dest="audit_log",
        default=None,
        help="Path to audit log file (default: ~/.sandboxshift/audit.log)",
    )
    tail_parser.set_defaults(func=_cmd_audit_tail)

    return parser


def main() -> None:
    """Entry point for the sandboxshift CLI."""
    parser = _build_parser()
    args = parser.parse_args()
    args.func(args)
