# Auto-generated by sandboxshift-setup.sh — do not edit manually.
# Re-run ./sandboxshift-setup.sh to regenerate.
#
# This file is a placeholder. sandboxshift-setup.sh overwrites it with
# real bucket/table names on first run.
terraform {
  backend "s3" {
    bucket         = "PLACEHOLDER-run-sandboxshift-setup.sh"
    key            = "sandboxshift/fargate/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "PLACEHOLDER-run-sandboxshift-setup.sh"
  }
}
